# Generated by Django 3.2.9 on 2021-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('landing', 'landing'), ('sale', 'sale'), ('other', 'other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='target_keywords',
            field=models.ManyToManyField(blank=True, null=True, to='pages.Keyword'),
        ),
    ]
