# Generated by Django 3.2.9 on 2021-11-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211114_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='target_keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
    ]
